[global]
ioengine=libaio
direct=1
iodepth=128
rw=write
bs=128k
numjobs=1
size=100%
group_reporting=1
time_based=1
ramp_time=120s
runtime=180s

[job1]
name=job1
filename=/dev/nvme3n1p1

[job2]
name=job2
filename=/dev/nvme3n1p2

[job3]
name=job3
filename=/dev/nvme3n1p3

[job4]
name=job4
filename=/dev/nvme3n1p4

[job5]
name=job5
filename=/dev/nvme3n1p5

[job6]
name=job6
filename=/dev/nvme3n1p6

[job7]
name=job7
filename=/dev/nvme3n1p7

[job8]
name=job8
filename=/dev/nvme3n1p8