[global]
ioengine=libaio
direct=1
iodepth=128
rw=write
bs=16k
numjobs=1
group_reporting=1
time_based=1
ramp_time=120s
runtime=180s
filename=/dev/nvme3n1

[job1]
name=job1
offset=0G
size=1598G

[job2]
name=job2
offset=1598G
size=1598G

[job3]
name=job3
offset=3196G
size=1598G

[job4]
name=job4
offset=4794G
size=1598G

[job5]
name=job5
offset=6392G
size=1598G

[job6]
name=job6
offset=7990G
size=1598G

[job7]
name=job7
offset=9588G
size=1598G

[job8]
name=job8
offset=11186G
size=1598G